name: feedback_app
description: A Feedback App created using flutter.
publish_to: 'none'
version: 1.5.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flare_flutter: ^3.0.2

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
   - assets/
